# Generated by Django 4.1.5 on 2023-04-11 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06b2be7f-ff40-45ad-86ac-51170d239632'), primary_key=True, serialize=False),
        ),
    ]
