# Generated by Django 4.1.5 on 2023-04-11 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d038ec52-9f7a-45a3-ac48-f56fdeea0f56'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15af0c0a-de67-4a50-b024-15207f6b1392'), primary_key=True, serialize=False),
        ),
    ]
