# Generated by Django 4.1.5 on 2023-04-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='categories',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(default='2f9c3f9b-df9d-41a9-af08-73444beade79', on_delete=django.db.models.deletion.CASCADE, to='movies.category', verbose_name='Category'),
        ),
    ]
