# Generated by Django 4.1.5 on 2023-04-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_categories_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieimage',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.category', verbose_name='Category'),
        ),
    ]
